const types = {
  // recipes
  FETCH_RECIPES: 'FETCH_RECIPES',
  ADD_RECIPE: 'ADD_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',

  // filter
  CHANGE_FILTER: 'CHANGE_FILTER',

  // create modal
  OPEN_CREATE_MODAL: 'OPEN_CREATE_MODAL',
  CLOSE_CREATE_MODAL: 'CLOSE_CREATE_MODAL',
};

export default types;
