const types = {
  // recipes
  FETCH_RECIPES: 'FETCH_RECIPES',
  ADD_RECIPE: 'ADD_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  UPDATE_RECIPE: 'UPDATE_RECIPE',

  // filter
  CHANGE_FILTER: 'CHANGE_FILTER',

  // creating
  CREATING: 'CREATING',

  // editing
  EDITING: 'EDITING',

  // create modal
  OPEN_CREATE_MODAL: 'OPEN_CREATE_MODAL',
  CLOSE_CREATE_MODAL: 'CLOSE_CREATE_MODAL',

  // edit modal
  OPEN_EDIT_MODAL: 'OPEN_EDIT_MODAL',
  CLOSE_EDIT_MODAL: 'CLOSE_EDIT_MODAL',
};

export default types;
